### ISSUE TITLE
Windows - Wiimote -TR reports no accelerometer data

### ISSUE THREAD

**Issue by phHartl** [wiiuse/wiiuse#105]
I'm currently able to successfully connect my Wiimote -TR with my Windows system (Windows bluetooth stack), after compiling Wiiuse and executing the provided example (master).

```
wiiuse v0.15.4 loaded.
  De-facto official fork at http://github.com/wiiuse/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> <https://sourceforge.net/projects/wiiuse/>
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:283: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:301: Calibrated wiimote acc

[DEBUG] io.c:325: Asking for status, attempt 44 ...

[DEBUG] wiiuse.c:545: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (22) 00 00 15 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x20
[DEBUG] (id 1) SEND: (17) 04 a6 00 fa 00 06
[DEBUG] (id 1) RECV: (22) 00 00 17 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] motion_plus.c:55: No Motion+ available, stopping probe.
[DEBUG] events.c:608: Setting timeout to normal 10 ms.
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[INFO] Connected to wiimote [id 1].
Connected to 1 wiimotes (of 1 found).
[DEBUG] (id 1) SEND: (11) 10
[DEBUG] wiiuse.c:225: Starting rumble...
[DEBUG] (id 1) SEND: (13) 11
[DEBUG] wiiuse.c:230: Stopping rumble...
[DEBUG] (id 1) SEND: (13) 10

Controls:
        B toggles rumble.
        + to start Wiimote accelerometer reporting, - to stop
        UP to start IR camera (sensor bar mode), DOWN to stop.
        1 to start Motion+ reporting, 2 to stop.

[DEBUG] (id 1) RECV: (22) 00 00 13 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

For university research purposes I need to access the accelerometer data, as well as the IR data provided by the Wiimote. However after pressing '+' on my Wiimote and rotating it wrong accelerometer data is reported:

```
[DEBUG] (id 1) RECV: (30) 10 00 13 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


--- EVENT [id 1] ---
PLUS pressed
[DEBUG] wiiuse.c:383: Setting report type: 0x31
[DEBUG] (id 1) SEND: (12) 00 31
wiimote roll  = 0.000000 [0.000000]
wiimote pitch = 0.000000 [0.000000]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (22) 10 00 12 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] (id 1) RECV: (30) 00 00 12 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


--- EVENT [id 1] ---
wiimote roll  = 0.000000 [0.000000]
wiimote pitch = 0.000000 [0.000000]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (30) 10 00 12 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


--- EVENT [id 1] ---
PLUS pressed
[DEBUG] wiiuse.c:383: Setting report type: 0x31
[DEBUG] (id 1) SEND: (12) 00 31
wiimote roll  = 0.000000 [0.000000]
wiimote pitch = 0.000000 [0.000000]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (22) 10 00 12 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] (id 1) RECV: (30) 00 00 12 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


--- EVENT [id 1] ---
wiimote roll  = 0.000000 [0.000000]
wiimote pitch = 0.000000 [0.000000]
wiimote yaw   = 0.000000

```
After browsing the repository I suspect a calibration problem similar to #88 which has been fixed last year for Linux.  Unfortunately I'm currently not able to check whether IR data works.

In the end I want to provide a python interface for this library but I need to get all sensor values to work first. 

Thanks in advance for any support :)

**Comment by janoc** [comment]
Hmm, that's odd. I doubt it is related to #88, there it was completely impossible to connect to a -TR type of Wiimote. You are getting connected and are receiving data. Receiving all zeros is rarely related to calibration (you would be receiving some data but they would be wildly off if it was a calibration problem) but rather some hardware/initialization issue. 

Unfortunately I don't have Windows development machine around, so I can't check it there but my -TR wiimote works OK in Linux. 

Things to verify:
- Make sure you are running the latest code from the master branch here. 
- Make sure you are connecting to the Wiimote using the battery compartment button and not by pressing the 1+2 together, like on the older Wiimotes. Nintendo has changed things and when pressing 1+2 together I have been able to connect to the controller sometimes but it wasn't working correctly. 
- If you can, try a different Bluetooth dongle - that unfortunately matters sometime, especially in Windows. There is a lot of broken hardware around :( 
- If you have any expansion (nunchuk, etc.) connected, unplug it and try without it first.
- Is your Wiimote a genuine Nintendo one or a clone? Clones often do weird things due to protocol differences and the vendor usually implementing only the bare minimum required to get it to talk to Wii. 
- Which version of Windows/Bluetooth stack are you using? If you aren't using Windows 10 and the default Microsoft stack, I would strongly suggest trying it with that first.

**Comment by janoc** [comment]
I have looked at your trace in more detail and there are a few weird things there:

`[DEBUG] io.c:325: Asking for status, attempt 44 ...`
This isn't normal, unless there is a ton of interference or you are far from the computer it shouldn't take this long. 44 attempts shows that something is really wrong with the Bluetooth link or the device.

`[DEBUG] motion_plus.c:55: No Motion+ available, stopping probe.`
This is definitely **not** normal. -TR has a built-in Motion+ and the code should detect it. You should see a message like:
`[DEBUG] /media/u/build/wiimote/wiiuse/src/motion_plus.c:73: Detected inactive Motion+!`

I do hope that Nintendo didn't change the Wiimote yet again :(

**Comment by phHartl** [comment]
Meanwhile I read some more issues here on Github and found this answer in #21 which seems to be exactly my problem:

> I still get this bug on Windows, all the older wiimotes work correctly. However, the latest version doesn't. I can correctly connect to the wiimote and rumble it, detect the buttons, but the accelerometer reports 0 everywhere.
> 
> _Originally posted by @lachose1 in https://github.com/wiiuse/wiiuse/issues/21#issuecomment-522134259_

Things I've already verified:

- I'm running the latest master code
- I use the sync button to connect to my Wiimote -TR
- I don't use any expansions at all
- My WiiMote is an originally Nintendo one
- Currently I'm using Win 10 with the MS Bluetooth stack (as written in my original post)
- I'm not able to check whether the dongle is the problem atm

My Wiimote is about 30 cm's away from my bluetooth dongle - so it shouldn't be the distance at all.

`[DEBUG] motion_plus.c:55: No Motion+ available, stopping probe.`

I wasn't sure whether this only means there is no separate Motion+ detected. But according to your answer it doesn't and therefore might be a huge problem.

**Comment by janoc** [comment]
> I wasn't sure whether this only means there is no separate Motion+ detected. But according to your answer it doesn't and therefore might be a huge problem.

No, that means that the code didn't detected any Motion+. There is no difference between the external (rare) add-on dongle Motion+ and a built-in one. So if the code doesn't detect it, it means there is some problem. 

Given that your Wiimote had issues with replying to the status request, I suspect it was not initialized correctly for whatever reason and the Motion+ failing is a consequence of that.

OK, I have looked in the code and I have no idea how did what you have in the trace happen. The `"[DEBUG] io.c:325: Asking for status, attempt 44 ...` message is impossible:

io.c from line 320:
`
        for (i = 0; i < 3; ++i)
        {
            int rc = 0;

            WIIUSE_DEBUG("Asking for status, attempt %d ...\n", i);
            wm->event = WIIUSE_CONNECT;

            wiiuse_status(wm);
            rc = wiiuse_wait_report(wm, WM_RPT_CTRL_STATUS, buf, MAX_PAYLOAD, WIIUSE_READ_TIMEOUT);

            if (buf[3] != 0)
                break;

            wiiuse_millisleep(500);
        }
`
How the heck did it even get to an attempt 44 when the loop runs only 3x max? WTF ... 

I am afraid I will need to ask you for help here, because I have no means to neither reproduce the bug nor debug it. Could you open the code in a debugger and see what is happening in this code, please?

**Comment by phHartl** [comment]
I attached a debugger at that location and the iteration variable _i_ is actually 0 instead of 44 (btw. while debugging it is attempt 12 instead of 44). The loop breaks after its first iteration, indicating a correct initialization? However, this seems not to be the case - after following each step inside the debugger wiiuse_wait_report() (inside io.c) returns -1 because of a communication timeout (I obviously placed the debug point at the return value to avoid my debug steps to cause this delay). Afterwards the method breaks because 

` if (buf[3] != 0)
                break;`

is true.

**Comment by janoc** [comment]
Be careful about stepping through that loop - the program is stopped but the Wiimote (obviously) isn't, so things are happening behind your back and the code will miss them. That's likely why you have got the 12 iterations (which is still wrong ...). 

Could you modify the code and add a printout of the variable there, please? Then run it and see what happens. I would expect to see regular iteration to max. 2, if it prints out something else then the stack has been smashed somewhere. 

BTW, if you have built the code with SDL (it is only needed for the SDL example), I suggest you disable it and rebuild it without to be sure that there is no Visual C runtime difference issue causing a random memory corruption.

**Comment by phHartl** [comment]
```
wiiuse v0.15.4 loaded.
  De-facto official fork at http://github.com/wiiuse/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> <https://sourceforge.net/projects/wiiuse/>
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:283: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] io.c:301: Calibrated wiimote acc

[DEBUG] io.c:325: Asking for status, attempt 12 ...

The iteration is: 0
[DEBUG] wiiuse.c:545: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (22) 00 00 15 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x20
[DEBUG] (id 1) SEND: (17) 04 a6 00 fa 00 06
[DEBUG] (id 1) RECV: (22) 00 00 17 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] motion_plus.c:55: No Motion+ available, stopping probe.
[DEBUG] events.c:608: Setting timeout to normal 10 ms.
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[INFO] Connected to wiimote [id 1].
Connected to 1 wiimotes (of 1 found).
[DEBUG] (id 1) SEND: (11) 10
[DEBUG] wiiuse.c:225: Starting rumble...
[DEBUG] (id 1) SEND: (13) 11
[DEBUG] wiiuse.c:230: Stopping rumble...
[DEBUG] (id 1) SEND: (13) 10

Controls:
        B toggles rumble.
        + to start Wiimote accelerometer reporting, - to stop
        UP to start IR camera (sensor bar mode), DOWN to stop.
        1 to start Motion+ reporting, 2 to stop.


[DEBUG] (id 1) RECV: (22) 00 00 13 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

I added a line to printout any iteration `printf("The iteration count is: %d\n", i);` - however as seen above (`The iteration is: 0`) it doesn't match with the wiiuse debug log. I did not compile the code with the SDL example yet.

**Comment by janoc** [comment]
I don't get it. Assuming you have added the print directly inside that loop and it is is printing the 'i' variable, which is the same thing being printed as the attempt count, then I don't see how those two can be different? 

Oh I see now - lovely bug ... WIIUSE_DEBUG expands to this on Windows (definitions.h, line 80):
```
#define WIIUSE_DEBUG(fmt, ...)                                                                      \
    do                                                                                              \
    {                                                                                               \
        if (OUTF_DEBUG)                                                                             \
        {                                                                                           \
            char *file = __FILE__;                                                                  \
            int i      = strlen(file) - 1;                                                          \
            for (; i && (file[i] != '\\'); --i)                                                     \
                ;                                                                                   \
            fprintf(OUTF_DEBUG, "[DEBUG] %s:%i: " fmt "\n", file + i + 1, __LINE__, ##__VA_ARGS__); \
        }                                                                                           \
    } while (0)
```
And that uses its own `i` variable. So that's a red herring then, the number of attempts is totally bogus because the wrong `i` is being printed. Who in their mind could have thought that using an `i` as a variable inside a macro is a good idea ... *facepalm*.

**Comment by janoc** [comment]
OK, one more thing to try. Since it seems the issue is somehow Motion+ related (that thing is never going to stop causing trouble ...) try to disable probing for it in events.c, from line 564:
```
    /* probe for Motion+ */
    if (!WIIMOTE_IS_SET(wm, WIIMOTE_STATE_MPLUS_PRESENT))
    {
        wiiuse_probe_motion_plus(wm);
    }
```
Just comment that out, rebuild and see what happens.

**Comment by phHartl** [comment]
I already tried to disable probing for Motion+ by commenting this code in motion_plus.c (line 52) out before:

```
// check error code 
    if ((buf[5] & 0x0f) == 0)
    {
        WIIUSE_DEBUG("No Motion+ available, stopping probe.");
        WIIMOTE_DISABLE_STATE(wm, WIIMOTE_STATE_MPLUS_PRESENT);
        return;
    }
```
But it didn't change anything unfortunately - the code breaks here afterwards (no valid Motion+ id): 

```
/* we have read something weird */
        WIIUSE_DEBUG("Motion+ ID doesn't match, probably not connected.");
        WIIMOTE_DISABLE_STATE(wm, WIIMOTE_STATE_MPLUS_PRESENT);
        return;
```

I recompiled with the changes you suggested but I didn't change anything unluckily. 

I really appreciate your help.

**Comment by janoc** [comment]
Yes, that really looks like some sort of problem with the Wiimote that is doing something different than the code expects. Error code 0x02 isn't even documented. I do hope it is not due yet another hardware variant :(

I am afraid I won't be able to help you much here without being able to reproduce this problem myself.

For your project I would suggest either trying with a different Wiimote, maybe you get lucky. Ideally try to find an older, non-TR one. 

Another option that works really really well in Windows is the Mayflash DolphinBar:
https://www.amazon.fr/Mayflash-Dolphinbar-Barre-Capteur-sans/dp/B00HZWEB74

You pair your Wiimote with this and then it behaves like a normal gamepad in Windows. It has multiple modes, I believe it was the last (4th) setting that acts as a pass-through and lets you use Wiiuse with it as if you have connected the controller directly to Windows. However, all the tricky initialization/connection stuff is handled for you by the hardware, eliminating the vagaries of the Windows Bluetooth stack.

**Comment by janoc** [comment]
I have also just realized that my -TR Wiimote fix for Linux may be actually not working for Windows. 

The change in Linux was swapping the command and data channels (low level Bluetooth issue) to make this controller work. The Windows side of things is using the high level HID API and isn't using the Bluetooth APIs at all - it relies on the OS to set things up correctly. So this may not even be fixable for Windows, at least not without a major rewrite :(

**Comment by phHartl** [comment]
Just to eliminate a possible error on my side. I connect my wiimote via the "Join a Personal Area Network" function inside Windows because after a major creators update you are not able to connect via the normal Bluetooth settings any more (it requires a PIN). Is this correct?

Luckily I have access to multiple Unix systems and I'll try to compile it there - I expect it to work though. Before using this library (especially for Windows) I already found working implementations for Linux using Python only. 

I checked the Python code and can confirm they also switched the command and data channel to communicate directly via L2CAP with the new wiimote -TR. Unfortunately under Windows there is no way to directly setup a L2CAP Bluetooth socket to my knowledge, which was the reason I have chosen this C library as the wiimote doesn't support communication via RFCOMM.

**Comment by phHartl** [comment]
```
wiiuse v0.15.4 loaded.
  De-facto official fork at http://github.com/wiiuse/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> <https://sourceforge.net/projects/wiiuse/>
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (XX:XX:XX:XX:XX:XX) [id 1].
[INFO] Connected to wiimote [id 1].
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55 
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] io.c:283: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08 
[DEBUG] (id 1) RECV: (22) 00 00 16 07 00 
[DEBUG] io.c:143: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (21) 00 00 70 00 16 80 7f 7e 22 9a 97 98 09 00 00 00 00 00 00 00 00 00 
[DEBUG] io.c:301: Calibrated wiimote acc

[DEBUG] io.c:325: Asking for status, attempt 0 ...

[DEBUG] wiiuse.c:545: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00 
[DEBUG] (id 1) RECV: (20) 00 00 10 00 00 52 00 
[DEBUG] (id 1) SEND: (17) 04 a6 00 fa 00 06 
[DEBUG] (id 1) RECV: (21) 00 00 50 00 fa 01 00 a4 20 00 05 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] motion_plus.c:73: Detected inactive Motion+!
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a600f0...
Write data is: 55 
[DEBUG] (id 1) SEND: (16) 04 a6 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55 
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] wiiuse.c:606: Writing 1 bytes to memory location 0x4a400fb...
Write data is: 0 
[DEBUG] (id 1) SEND: (16) 04 a4 00 fb 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
Connected to 1 wiimotes (of 1 found).
[DEBUG] (id 1) SEND: (11) 10 
[DEBUG] wiiuse.c:225: Starting rumble...
[DEBUG] (id 1) SEND: (13) 11 
[DEBUG] wiiuse.c:230: Stopping rumble...
[DEBUG] (id 1) SEND: (13) 10 

Controls:
	B toggles rumble.
	+ to start Wiimote accelerometer reporting, - to stop
	UP to start IR camera (sensor bar mode), DOWN to stop.
	1 to start Motion+ reporting, 2 to stop.


[DEBUG] (id 1) RECV: (22) 00 00 16 00 00 
[DEBUG] (id 1) RECV: (22) 00 00 16 07 00 
[DEBUG] (id 1) RECV: (22) 00 00 16 07 00 


--- EVENT [id 1] ---
PLUS pressed
[DEBUG] wiiuse.c:383: Setting report type: 0x31
[DEBUG] (id 1) SEND: (12) 00 31 
wiimote roll  = 0.000000 [0.000000]
wiimote pitch = 0.000000 [0.000000]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (31) 10 40 83 7e 98 00 


--- EVENT [id 1] ---
PLUS pressed
wiimote roll  = 0.460736 [6.581944]
wiimote pitch = -0.165917 [-2.370236]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (31) 70 40 82 7e 98 00 


--- EVENT [id 1] ---
PLUS pressed
wiimote roll  = 2.170664 [4.398705]
wiimote pitch = -0.837325 [-2.378924]
wiimote yaw   = 0.000000
[DEBUG] (id 1) RECV: (31) 50 40 82 7e 98 00 

```

This is my output under Linux (Manjaro - 5.3.12). Here the right wiimote type gets detected automatically (`[INFO] Found wiimote (type:  (motion plus inside)) (XX:XX:XX:XX:XX:XX) [id 1]`) and the accelerometer works (except the yaw somehow). The wiimote also return reports of type 31 instead of 30 in Windows.

**Comment by janoc** [comment]
Hum that sounds correct but I haven't used a Wiimote in Windows in a while. So not sure what exactly has changed and how there. It should still be possible to connect it without pairing, otherwise there are some utilities online that permit to pair it (the PIN code is the bluetooth MAC address reversed but you can't type that due to the bytes not being printable characters). 

You can create L2CAP connections in Windows but that API is only available for device drivers, AFAIK. So can't be really used by "mere mortals". 

If you get the device running in Linux, you could easily use Wiimote there and just talk to it over network. That is a setup we have been using at work with the Sony PlayStation Move controllers (which didn't work in Windows at all). A Raspberry Pi (the recent ones have even Bluetooth and Wifi built-in, so no dongles needed) and run e.g. VRPN server there for the application to connect to. The latency is generally low enough for this to be usable even for virtual reality.

**Comment by janoc** [comment]
Yes, that is exactly the same output I am getting. So the Wiimote is fine, it is really problem with the Window protocol implementation.

**Comment by phHartl** [comment]
The accelerometer not measuring yaw makes definitely sense - I simply forgot to turn on Motion+. I'm still curious why exactly only buttons and rumble is working but everything else seems to be broken on Windows.

> The original Wiimotes (RVL-CNT-01) allowed sending commands using SET REPORT (0x52) over the control pipe, instead of using the data pipe; however, this form does not work on the newer RVL-CNT-01-TR, and as such is not recommended. 
> by [wiibrew](http://wiibrew.org/wiki/Wiimote#Data_Reporting)

If Windows only sends commands using the control pipe, why do you get any information at all back then? It seems like report type 30 might be the default one?

**Comment by janoc** [comment]
I think it was like that even in Linux - the statement that "it does not work" shouldn't be taken as "it does not work at all" but that you may get undefined behavior. The button report is the default, yes. 

So the issue is that changing to any other type of report or sending commands to turn off encryption, initialize the Motion+ or any other expansion is most likely simply ignored by the newer Wiimote when sent over the control pipe.

**Comment by phHartl** [comment]
So in the end it seems like this code part in os_win.c (line 345) sends only data on the control pipe instead of the data pipe I guess? :
```
 case WIIUSE_STACK_MS:
        return HidD_SetOutputReport(wm->dev_handle, write_buffer, len + 1);
```

**Comment by janoc** [comment]
Well, I have no means to verify that, given that it is Windows SDK code, but I would assume that, yes. Setting report types is something that is handled over the control endpoint in HID, not interrupt (data) endpoints. 

Wiimote is a bit of a non-standard oddity in this regard - the console vendors don't design their hw to work with anything else than their consoles, so they don't bother with things like standard compliance ...

**Comment by phHartl** [comment]
According to [this](https://github.com/jloehr/Wiimote-HIDAPI) repository one should use `WriteFile` instead of `HidD_SetOutputReport` to communicate with the new Wiimote -TR, because Writefile seems to send data via the data channel.

**Comment by janoc** [comment]
That's interesting. Are you able to test this? It shouldn't be difficult to replace the calls, the arguments are pretty similar there.

**Comment by janoc** [comment]
In fact, there **is** an implementation using WriteFile already - if one uses the Bluesoleil stack! So you could just copy that line and see if it works. If it does, please make a pull request, I will be happy to merge this.

**Comment by phHartl** [comment]
The wiimote now connects almost instant instead of taking about 5 - 10 seconds & the accelerometer works! However still no Motion+ values are reported - I'll investigate.

**Comment by janoc** [comment]
Oh cool! The Motion+ needs to be explicitly enabled - I believe it is the '1' and '2' buttons that control it once motion reporting is enabled.

**Comment by phHartl** [comment]
I already pressed the '1' button but still no values are reported. It works if I comment out this code part:

```
if (!WIIMOTE_IS_SET(wm, WIIMOTE_STATE_MPLUS_PRESENT) || WIIMOTE_IS_SET(wm, WIIMOTE_STATE_EXP_HANDSHAKE))
    {
        return;
    }
```
More specifically the first condition seems to be wrong - the state returned by the wiimote is 0x80D vs the expected 0x80000.

**Comment by janoc** [comment]
Hum, did you put the Motion+ probing back after the tests earlier? This looks like it doesn't detect it.

**Comment by phHartl** [comment]
Turns out I just had to reconnect my wiimote. The error is gone now. I'll make a pull request soon.

**Comment by janoc** [comment]
Cool so it works? That's a great news. Those spurious reports are harmless, Wiimote isn't completely reverse engineered so there are likely some things we don't know yet.

**Comment by phHartl** [comment]
Feel free to check out the pull request #106.

**Comment by janoc** [comment]
Thanks a lot, I am making a new release and we can hopefully put the issues with the -TR Wiimote to rest thanks to your efforts.
