### ISSUE TITLE
Wii Balance Board not properly initializing

### ISSUE THREAD

**Issue by albianto** [wiiuse/wiiuse#107]
One of the first symptoms is that calibration data is missing from the `wii_board_t` structure and this causes empty data on `tl`, `tr`, `bl` and `br` fields even though the raw sensor values is received properly.
Other times the balance board doesn't even go into data streaming mode and no updates are received.
It can be fixed by repeatedly trying to connect and disconnect.
Then I also started paying attention to random crashes in the example project, usually at os_win.c:293 for corrupted stack around `buf` variable.

https://github.com/wiiuse/wiiuse/blob/dfbe3d2cd21d3d88d7ba9de39cfc8aa901a6041b/src/os_win.c#L292-L302

I then noticed that in those cases ReadFile at os_win:253 returns `ERROR_IO_PENDING`.
https://github.com/wiiuse/wiiuse/blob/dfbe3d2cd21d3d88d7ba9de39cfc8aa901a6041b/src/os_win.c#L253

This randomly happens a few times during the handshake phases.

After a lot of poking around, disabling `FILE_FLAG_OVERLAPPED` seems to have fixed the issue for me and results in what it seems a 100% reliable handshake (need to do more testing on this).
https://github.com/wiiuse/wiiuse/blob/dfbe3d2cd21d3d88d7ba9de39cfc8aa901a6041b/src/os_win.c#L109-L112

I don't have a lot of experience with Win32 stuff, so I couldn't understand why this flag was there in the first place (I read from the docs that it enables asynchronous IO but I don't get why this is required if we're polling anyway).

I wanted to know if anybody that knows more can further expand on this and tell me if there are any implication to this change.

My setup: Windows 10, VS2019
Either 10 SDK, VS2019 Build Tools and 8.1 SDK, VS2017 Build Tools give same results.

**Comment by janoc** [comment]
Hum, thanks for investigating this. The flag could be a historical leftover, the handshaking code has been modified several times since this has been written. Indeed, use of that flag makes no sense, because the code can't meaningfully continue if the data hasn't been received. 

Please try to check that this modification doesn't cause any regressions with the regular Wiimote, especially when Motion+ is enable. If it doesn't, feel free to make PR, I will merge it.

**Comment by edo42** [comment]
Could it possibly be used to handle disconnection while reading? I suppose the `ReadFile` command should return an error code in this case even if it's waiting synchronously.

Unfortunately I've only got a Balance Board so I cannot test the regular Wiimote.
I'll do some further testing and make a pull request if I don't find any issues.

**Comment by janoc** [comment]
I don't think it is necessary for the disconnection. I would test it but I don't have a Windows machine around, only Linux :(
