### ISSUE TITLE
WiiBoard calibration

### ISSUE THREAD

**Issue by janoc** [wiiuse/wiiuse#108]
Moved question by @DanhuaZhang from #104 

> Hi, I have the question for the center of pressure data: How to calibrate the axis values? Why the default is (1, -1) rather than (0, 0)? What does the axis look like? (the origin and the direction the two axes are pointing to)

**Comment by janoc** [comment]
I am not sure what are you referring to. 

There are no predefined "axes" on the Wiiboard. The board reports the pressure on the 4 corners (tl = top left, tr = top right, bl = bottom left, br = bottom right), which, ideally, should be mass in kilograms. 

If you are referring to this code in `example.c`:
```		
float x = ((wb->tr + wb->br) / total) * 2 - 1;
float y = ((wb->tl + wb->tr) / total) * 2 - 1;
```
Then that is only an arbitrary choice of the original author of the example. You can define the meaning of `x` and `y` as you want, including the ranges of the values. 

I believe the idea was to have a value 0 represent the situation when there is someone **standing** on the board (not the empty, unloaded board!) in the center. Then you can have positive values on the side where you apply pressure to (= lean towards it) and negative ones on the unloaded side. However, that is only one way to do it. The library gives you the 4 weights and you do what you want with them.

**Comment by DanhuaZhang** [comment]
Sorry to reply late. The information you provided is sufficient for me. Thank you very much for sharing!

**Comment by janoc** [comment]
You are welcome.
