### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by rperrot** [wiiuse/wiiuse#109]
Hi, 

does anyone know if the library could be used in a multithread way ? 

In my tests, if I launch wiiuse_init in main thread then if I use wiiuse_find in an other thread, the call to wiiuse_find never ends (even after minutes). If the two calls are in the same thread, there is no issue. 

Is there any limitation or option to allow the use in a multithread environment ? 

(Note: I only tested on macOS).

Thanks.

**Comment by janoc** [comment]
Wiiuse is not threadsafe. There is no way to do that without wrapping every call to the system APIs with mutexes which would be extremely inefficient. If you need this, then you need to provide your own synchronization. 

Also, your use case likely points to a problem with thread-local storage - the APIs Wiiuse uses are certainly not designed to be called from multiple threads simultaneously, so there isn't a whole lot we can do about that (for example, OpenGL contexts are like that as well). 

Why do you need to call wiiuse_init and wiiuse_find from different threads? That sounds like an application design issue to me. If you want to be able to scan for Wiimotes asynchronously, then just maintain a background worker thread that deals with Wiiuse (initializes it and then runs the main polling loop) and will pass messages/events/whatever to your application thread(s).

**Comment by rperrot** [comment]
Thanks for your answer. 

The issue is not to be used from multiple threads simultaneously, I managed to use mutex for that. But I do not control how the threads are generated. 

My goal is to provide a WebSocket wrapper around wiiuse in order to use wiiuse inside a browser. In that system, each new command is executed inside a new thread (that's why wiiuse_find is not used in the same thread as wiiuse_init). 

I tried the solution you suggested (having a unique thread that execute the wiiuse commands and pass from message from/to the other threads) but it gives me the same behavior: calling wiiuse_init is Ok, but wiiuse_find is blocking and never ends. 

Can it be a macOS limitation ? (Again: if called from the main thread the functions behaves correctly).

**Comment by janoc** [comment]
It could be a MacOS limitation but I am not a Mac developer nor familiar with the Mac Bluetooth stack, so I can't really answer that. What is it blocking on inside wiiuse_find()? 

One way around this could be making the Wiiuse "server" application run the code on the main thread. Possibly not ideal, depending on how your application is designed.

**Comment by rperrot** [comment]
I think it's a macOS limitation and there some clue here : 

https://stackoverflow.com/a/59833390

> This requirement is not documented, and it can lead to all kinds of environment-dependent behavior, but mostly it leads to unsuccessful searches.

> In general, the safest approach is to do the device search in a separate process.

So I think multi-threading is not possible on macOS and I'll have to provide a separate process for wiiuse and use IPC.

**Comment by janoc** [comment]
Ah. That would certainly explain the issue. It doesn't surprise me, though - generally speaking, anything that talks to hw or makes syscalls is rarely thread-safe.

**Comment by PureTryOut** [comment]
Note that at least on Linux I can use it multi-threaded just fine. I have `wiiuse_init()` in a class constructor (C++), constantly run `wiiuse_find()` in a thread of that class to keep detecting any new Wiimotes, and run `wiiuse_poll()` in yet another thread to process events from any already connected Wiimotes. Works as expected so I wouldn't consider your problem a library bug (and thus this issue can be closed right?).

**Comment by janoc** [comment]
Careful that **is not safe**. It may work (for some definition of work) but if you have one thread doing `wiiuse_poll()` and another in parallel accessing the wiimote datastructures (or even running `wiiuse_find()`), you **will** have race conditions! 

E.g. the `wiiuse_find()` function modifies its first argument with the `wiimote_t` structures that likely your `wiiuse_poll()` operates on (unless you are copying the data somehow).

Also the Bluetooth API is not thread safe. 

Please, don't do this. That is asking for problems. Feel free to run the Wiimote stuff on a separate thread if you must but don't access its data/call functions from multiple threads at once.

**Comment by PureTryOut** [comment]
> unless you are copying the data somehow

Nope, pointers everywhere. Hmm well that is good to know, although I had no problems so far it's probably pure luck then.

OK well then I have a problem. I don't want to just detect devices once and then start listening for events, I want to constantly connect to any new devices if found _while_ checking for events in existing devices. If `wiiuse_find()` didn't block that would be doable in a thread-safe manner then, but it does block so the only way of doing it would be calling `wiiuse_find()` only once. Is that really how Wiiuse is meant to be used? Once you've connected a device and you've started listening for events, you can't connect any other devices anymore?

**Comment by janoc** [comment]
Yeah that's a bit of an unfortunate design decision by the original author(s). The idea is that you turn all your devices on at once (e.g. in Windows you even need to connect to the beforehand!) and then you start Wiiuse which will detect them and start using them. 

There is no support for any kind of dynamic hotplugging of Wiimotes whatsoever. There is only some limited support for hotplugging expansions. 

The only thing you could do is to periodically "stop everything" (to avoid touching the shared state), call `wiiuse_find()` and then resume, handling any initialization/handshaking for newly detected devices that you may have to do first and also deal with errors due to disconnected hardware. That is going to be very fragile, to say the least ...

That's why I was talking about needing to support D-BUS, for example, if we were to implement #66 - that is the correct way to get hotplugging support for Bluetooth devices in Linux.

**Comment by PureTryOut** [comment]
Yeah ok, guess the design of this library doesn't fit what I want then. Sad, back to XWiimote I go :sweat_smile:

**Comment by janoc** [comment]
Sorry about that. I remember Cwiid was designed around asynchronous use but I am not sure what its current state is.

**Comment by PureTryOut** [comment]
[Last commit in 2010](https://github.com/abstrakraft/cwiid), 11 years ago, not very promising... Oh and the website is down. There is a fork with last commit in 2020 but they lost their complete git history and also seems unmaintained at the moment. Wii peripherals on PC is in a sad state of affairs :cry:

**Comment by janoc** [comment]
Yes, it sucks :( Sadly not many people want to actually contribute to changing that and I am grateful for any PR and patch that I get for Wiiuse. 

I think that apart Dolphin Emulator Wiiuse is the only Wii-related project that is still being actively maintained - and even that is only after it has been abandoned by its original author.
