### ISSUE TITLE
Stuck on some bluetooth stack problems

### ISSUE THREAD

**Issue by Tengato** [wiiuse/wiiuse#113]
Hi,
I have been trying to get the Wiiuse example to work and I ran into some issues (posting here since the librelist.com email doesn't work):
The cmake build for visual studio 2019 had the x64 projects pointing to the x86 versions of the Windows SDK, so I just manually changed them:
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\hid.lib
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\SetupAPI.Lib

Once I build and run the example while my Wiimote is paired, it seems to identify a wiimote device, but then says it can't determine the Bluetooth stack type when it calls wiiuse_set_report_type().  I tried just initializing the stack type to WIIUSE_STACK_MS, but again in wiiuse_set_report_type(), the call to WriteFile() returns 0, which seems to mean reject that device. So the example can't get past wiiuse_find()...

If someone could help point me in the right direction to get this working, I would be grateful!

btw, I'm using the Julian Loehr Wiimote drivers: https://www.julianloehr.de/educational-work/hid-wiimote/

Thanks :)

**Comment by janoc** [comment]
Hello,

Could you try without the Julian Loehr's driver? That driver will "grab" the connected Wiimote device and I am almost certain it will prevent Wiiuse from accessing while it is active. Wiiuse requires a fairly low level access to the hardware. 

The stack detection in os_win.c is done by attempting a HID driver call, same as wiiuse_set_report_type() uses. So if your driver above interferes with it or returns something else than the code expects, it could well explain your problem. 

Jan

**Comment by Tengato** [comment]
Aha, that was the problem - thanks so much!

**Comment by janoc** [comment]
Glad to hear it is solved! 

Debugging Windows Bluetooth bugs is a lot of "fun" otherwise.
