### ISSUE TITLE
Unhandled exception thrown: read access violation. **buf** was 0xFFFFFFFFFFFFFFFF.

### ISSUE THREAD

**Issue by Rakli17** [wiiuse/wiiuse#115]
Hey Again 
I am not sure that this is actual an issue or what but from time to time i get this unhandle exceptions thrown in the start up this is still while i just run the default example program.  

Do you have an idea of what to make of it. 

THNX 

Rasmus

**Comment by janoc** [comment]
Hello Rasmus, 

Without a stack trace it is completely impossible to help you or even to judge whether the problem is actually in Wiiuse. 

The error you have is because you are trying to read from memory that is not valid, most likely some sort of pointer problem.

**Comment by Rakli17** [comment]
Hej sorry for the late responds but here is the output and the callstack: 


'Controller.exe' (Win32): Loaded 'C:\Users\Bruger\source\repos\Controller\x64\Debug\Controller.exe'. Symbols loaded.
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Users\Bruger\source\repos\Controller\x64\Debug\wiiuse_debug.dll'. Symbols loaded.
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. 
The thread 0x16a4 has exited with code 0 (0x0).
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
Exception thrown at 0x00007FFE38A125D4 (wiiuse_debug.dll) in Controller.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
Unhandled exception thrown: read access violation.
**buf** was 0xFFFFFFFFFFFFFFFF.


the call stack: 
>	wiiuse_debug.dll!wiiuse_os_read(wiimote_t * wm, unsigned char * buf, int len) Line 295	C
 	wiiuse_debug.dll!wiiuse_wait_report(wiimote_t * wm, int report, unsigned char * buffer, int bufferLength, unsigned long timeout_ms) Line 134	C
 	wiiuse_debug.dll!wiiuse_handshake(wiimote_t * wm, unsigned char * data, unsigned short len) Line 329	C
 	wiiuse_debug.dll!wiiuse_os_find(wiimote_t * * wm, int max_wiimotes, int timeout) Line 148	C
 	wiiuse_debug.dll!wiiuse_find(wiimote_t * * wm, int max_wiimotes, int timeout) Line 68	C
 	Controller.exe!main() Line 36	C++
 	[External Code]	

this happens from time to time. 
Another thing is that it again from time to time dos not reconise that it is a motion plus controller wich in my program is keen for the whole aplication. any ideas here again: 

'Controller.exe' (Win32): Loaded 'C:\Users\Bruger\source\repos\Controller\x64\Debug\Controller.exe'. Symbols loaded.
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Users\Bruger\source\repos\Controller\x64\Debug\wiiuse_debug.dll'. Symbols loaded.
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. 
The thread 0x5a8 has exited with code 0 (0x0).
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'Controller.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 

[DEBUG] wiiuse.c:545: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (7a) 7c 7b 29 93 94 93 0b cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[DEBUG] io.c:144: (id 1) dropping report 0x7a, waiting for 0x20
[DEBUG] (id 1) RECV: (22) 00 00 16 07 16 7a 7c 7b 29 93 94 93 0b 00 00 00 00 00 00 00 00
[DEBUG] io.c:144: (id 1) dropping report 0x22, waiting for 0x20
[DEBUG] (id 1) RECV: (20) 00 00 10 00 00 77 7c 7b 29 93 94 93 0b 00 00 00 00 00 00 00 00
[DEBUG] (id 1) SEND: (17) 04 a6 00 fa 00 06
[DEBUG] (id 1) RECV: (cc) cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[DEBUG] io.c:144: (id 1) dropping report 0xcc, waiting for 0x21
[DEBUG] (id 1) RECV: (cc) cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[DEBUG] io.c:144: (id 1) dropping report 0xcc, waiting for 0x21
[DEBUG] motion_plus.c:68: Motion+ ID doesn't match, probably not connected.
[DEBUG] events.c:608: Setting timeout to normal 10 ms.
[DEBUG] wiiuse.c:383: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[INFO] Connected to wiimote [id 1].
Connected to 1 wiimotes (of 1 found).
[DEBUG] (id 1) SEND: (11) 10
[DEBUG] wiiuse.c:225: Starting rumble...
[DEBUG] (id 1) SEND: (13) 11
[DEBUG] wiiuse.c:230: Stopping rumble...
[DEBUG] (id 1) SEND: (13) 10

And final question is there a way to call calibration on both the accelrometer and the gyro ? 

Thank You in advance

**Comment by janoc** [comment]
That acccess violation crash looks like some Windows Bluetooth issue/problem with the Bluetooth dongle. That seems like the device has disconnected and then you get an error attempting to read from invalid memory.

Try with a different Bluetooth dongle if you can, also make sure the Wiimote doesn't disconnect while the application is running (i.e. don't press the power button, use weak batteries or be out of range).

Re Motion+ problem - your Wiimote is sending invalid data for whatever reason. If it is not a genuine Nintendo Wiimote but a clone then all bets are off. If it is a genuine one,  then see above - it is well possible you have some kind of communication/range issue that causes the data to be corrupted/packets lost. Or try with a different Wiimote first, it could be the wiimote itself that has a problem. 

Re calibration - what do you mean? There is some scale/offset calibration done automatically when both accelerometer and gyro are enabled using the factory data stored in the Wiimote. If you need more or different calibration than this, you need to do it yourself.

**Comment by Rakli17** [comment]
First of thanks for the quick response 

the bluetooth problem, is my build in bluotooth on my laptop i will try and get a dongle use that instead. 

the motion plus controller is a genuine and i think it is infact the bluetooth problem that unfolds to this that there is som packet lost.

**Comment by janoc** [comment]
That could well be the case. If there are bluetooth communication issues and invalid data are being returned (as you can see from those 0xcc values being read), then nothing will work right. 

Also Motion+ is notoriously finicky, the Wiimote needs very specific message sequence and timing to initialize which is difficult to get, esp. in Windows. Also the protocol relies on a lot of special cases for the Motion+, which was obviously a late bolt-on by Nintendo. For Wii it doesn't matter because they can handle this in the firmware but trying to make this work through generic HID layer (like with Windows) is a major pain.
