### ISSUE TITLE
Silence library output

### ISSUE THREAD

**Issue by PureTryOut** [wiiuse/wiiuse#119]
Currently Wiiuse prints out a lot of info to stdout and stderr, most stuff the user of my program shouldn't care about. I'd like to deal with errors and stuff myself and print things when _I_ find it necessary, not when the library likes too. Is it possible to get all output silenced? I find it weird for a library to print anything at all to be honest.

**Comment by janoc** [comment]
Make sure you are not building in DEBUG mode (CMake builds DEBUG by default unless you specify RELEASE, IMO). 

That will silence a lot, if not most, output.

**Comment by PureTryOut** [comment]
I built it with `-DCMAKE_BUILD_TYPE=Release`, so yes build mode is set to Release.

Still I get the following:

```
wiiuse v0.15.5 loaded.
  De-facto official fork at http://github.com/wiiuse/wiiuse
[INFO] Found 0 bluetooth device(s).
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (B8:AE:6E:31:79:3E) [id 1].
[INFO] Connected to wiimote [id 1].
```

**Comment by janoc** [comment]
Those are normal. 

However, if you really want to silence even that, you can set the output device to NULL and it will silence those:

Use the function: `void wiiuse_set_output(enum wiiuse_loglevel loglevel, FILE *logtarget);` 

loglevel should be LOGLEVEL_INFO and set logtarget to NULL (or an open file if you prefer to write those outputs to a logfile instead).

**Comment by PureTryOut** [comment]
Yup, I want to silence even those. Imo a library should never print out anything and leave that up to the application that uses the library. Any errors should be thrown to the application developer and let them handle it however they want, either informing the user or handle it silently.

Not a fan of the banner but that isn't so bad, I can live with it.

I just gave `wiiuse_set_output(LOGLEVEL_INFO, NULL);` a shot but it changed nothing :thinking:

**Comment by janoc** [comment]
I agree with you in general but we have all inherited this project. 

Changing/redoing all the logging inside the library would be quite some work. Furthermore, given that this is a C library and there is a lot of asynchronous/event-based code, there are often no good ways how to "throw the error to the application developer". The library architecture is just not designed for it. 

In that case reporting the problem to the console is the lesser evil, especially when dealing with hardware like the Wiimote and its expansions with their myriads of bugs and weird quirks.

Re `wiiuse_set_output()` - make sure to do it **after** calling `wiiuse_init()` (this one sets the output devices to stderr) but **before** calling `wiiuse_find()` (this one triggers the INFO output you have seen).

**Comment by PureTryOut** [comment]
Ah doihg it after `wiiuse_init()` is what I was missing, thanks!

I get that you have legacy baggage, that's why I'm fine with this solution. Thanks for your answer!
