### ISSUE TITLE
Plugging in a nunchuk often results in no events for a while and failure to read expansion type

### ISSUE THREAD

**Issue by PureTryOut** [wiiuse/wiiuse#120]
This happens even with the included `wiiuseexample`.

```
--- EVENT [id 1] ---
[WARNING] Unknown expansion type. Code: 0xffffffff
[WARNING] Could not handshake with expansion id: 0xffffffff
```

That event came in a few seconds after plugging in the expansion, and while that was happening no other events were processed.

**Comment by janoc** [comment]
That means your hardware has some issue. 0xffffffff is not a valid expansion type, most likely there is a poor connection and that results in data being read as all 1s. Expansions use I2C bus - that is an open collector/drain bus and if there is nothing connected, the pull-up resistors will ensure there is logic 1 on the wire. 

There isn't much the library can do with this.
