### ISSUE TITLE
MinGWSearchPathExtras.cmake got removed but was necessary

### ISSUE THREAD

**Issue by jcelerier** [wiiuse/wiiuse#130]
It is used when building under MinGW on windows :-)

cheers

**Comment by janoc** [comment]
Hello, 

I have restored the file. 

However, if you want MinGW support then please do have a look at #126 It does need some love and without someone actually using MinGW contributing fix for the build, MinGW won't be usable. 

Best regards,

Jan

**Comment by jcelerier** [comment]
hmm this is weird, I use it on my fork (https://github.com/ossia/wiiuse) and it  does not have this error there

**Comment by jcelerier** [comment]
here's my current patch set

**Comment by jcelerier** [comment]
(here are the same patches spread out over multiple commits : https://github.com/wiiuse/wiiuse/compare/master...ossia:wiiuse:wiiuse_master)

**Comment by janoc** [comment]
Could you perhaps extract the relevant bits and make a pull request out of it? I would be happy to merge it if it works. 

However, do keep in mind that it shouldn't break MSVC build, so careful with MinGW specific changes - MSVC is the primary target on Windows.
