### ISSUE TITLE
Windows disconnect event?

### ISSUE THREAD

**Issue by arpruss** [wiiuse/wiiuse#136]
wiiuse_poll() doesn't seem to return disconnect events under Windows. I get the disconnect message on stderr, but no event is reported when polling.

**Comment by janoc** [comment]
That's odd but given that the Windows code goes through the OS HID layer, it is perhaps normal. I don't have Windows machine around to test this but you could put a breakpoint in the `wiiuse_disconnected()` function and see whether it gets called.

Normally the Windows code does this (os_win.c):

```cpp
int wiiuse_os_read(struct wiimote_t *wm, byte *buf, int len)
{
    DWORD b, r;

    if (!wm || !WIIMOTE_IS_CONNECTED(wm))
    {
        return 0;
    }

    if (!ReadFile(wm->dev_handle, buf, len, &b, &wm->hid_overlap))
    {
        /* partial read */
        b = GetLastError();

        if ((b == ERROR_HANDLE_EOF) || (b == ERROR_DEVICE_NOT_CONNECTED))
        {
            /* remote disconnect */
            wiiuse_disconnected(wm);
            return 0;
        }
...
```

So if the `ReadFile()` call fails it should report the disconnect event. However, it is possible that the newer Windows return something else than ERROR_HANDLE_EOF or ERROR_DEVICE_NOT_CONNECTED. 

If you could reproduce the problem and check what gets returned I would add it to the code.

**Comment by janoc** [comment]
Well, the `wiiuse_os_poll()` function does this:

```c++
...
    for (i = 0; i < wiimotes; ++i)
    {
        wm[i]->event = WIIUSE_NONE;

        /* clear out the buffer */
        memset(read_buffer, 0, sizeof(read_buffer));
        /* read */
        if (wiiuse_os_read(wm[i], read_buffer, sizeof(read_buffer)))
        {
            /* propagate the event */
            propagate_event(wm[i], read_buffer[0], read_buffer + 1);
            evnt += (wm[i]->event != WIIUSE_NONE);
        } else
        {
            /* send out any waiting writes */
            wiiuse_send_next_pending_write_request(wm[i]);
            idle_cycle(wm[i]);
        }
    }
...
```

So that the previous error/event gets cleared after calling `wiiuse_poll()` is normal and intended.  That sounds more likea bug in your code checking for the event too late, to be honest. If `wiiuse_disconnected()` is called on your side (and the `wm` pointer is valid, obviously), then the event flag will be set by that function.

**Comment by arpruss** [comment]
But if wiiuse_poll() always clears the disconnect event, then what is the right way to check for disconnect in the code?
