### ISSUE TITLE
Which SDL-version required for example?

### ISSUE THREAD

**Issue by s5m4** [wiiuse/wiiuse#137]
What version of SDL is required for the SDL-example? (located at _wiiuse-0.15.5/example-sdl/sdl.c_)

I tried with SDL versions 2.26.5, 2.0.8, 2.0.3, 2.0.0., 1.0.2, 1.1.3. (and more) but keep getting errors during compilation. (see below) 

I am naively assuming it might be related to the required SDL-version (undeclared sld-identifiers, wrong argument numbers, also the errors change with different sdl versions, but are of the same types of errors.)

Here is the error log from compilation in Visual Studio 2022:

```
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(320,52): error C2065: 'SDL_RESIZABLE': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(320,64): error C2065: 'SDL_OPENGL': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(391,2): warning C4013: 'SDL_GL_SetAttribute' undefined; assuming extern returning int
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(391,41): error C2065: 'SDL_GL_DOUBLEBUFFER': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(392,39): error C2065: 'SDL_GL_DEPTH_SIZE': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(397,52): error C2065: 'SDL_RESIZABLE': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(397,64): error C2065: 'SDL_OPENGL': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(427,25): error C2065: 'SDL_VIDEORESIZE': undeclared identifier
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(429,27): error C2039: 'resize': is not a member of 'SDL_Event'
3>D:\mypath\SDL-1.0.2\include\SDL_events.h(127,15): message : see declaration of 'SDL_Event'
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(429,43): error C2039: 'resize': is not a member of 'SDL_Event'
3>D:\mypath\SDL-1.0.2\include\SDL_events.h(127,15): message : see declaration of 'SDL_Event'
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(429,7): error C2198: 'resize_window': too few arguments for call
3>D:\mypath\wiiuse-0.15.5\example-sdl\sdl.c(427,5): error C2051: case expression not constant
```

Any help is very much apreciated.

**Comment by janoc** [comment]
1.2.15 works. 

OTOH, that example is old (that's why the old SDL version) and not maintained very much, using really bad OpenGL code to draw a teapot. So I wouldn't really recommend using it.

If you need an example how to integrate Wiiuse use rather the normal non-SDL example and integrate the library with the SDL's main loop yourself. And if you want to do some 3D using a Wiimote there are much better frameworks to do that than the 1990's style glBegin()/glEnd() OpenGL this example uses.

**Comment by s5m4** [comment]
Thank you! I miss glBegin()/glEnd() but I get the point. I was just looking to find as much usage examples of the wiiuse library, not specifically the opengl stuff. The library works in my non-3D application and it's a charm. If I decide to add a 3D gui component to my interactive wiimote audio app, do you have a 3D framework you can recommend?

**Comment by janoc** [comment]
>do you have a 3D framework you can recommend?

No, not really. That is not possible to recommend without knowing the details about your application, your skill level and what do you want to actually achieve with it. There is no one size fits all solution here.
