### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mak448a** [wiiuse/wiiuse#138]
How do I use this library? I installed it from pypi, and I couldn't find much documentation

**Comment by qwertychouskie** [comment]
I'd start with https://github.com/wiiuse/wiiuse/tree/master/example

**Comment by janoc** [comment]
Hello, 

Not sure why did you install this via `pypi` (and how it did even get there in the first place, given that this isn't a Python library). 

This is a C/C++ library, please follow the provided examples on how to use this. 

If you are attempting to use this from Python (given that you have installed it from `pypi`), there I can't help you as no idea what kind of Python bindings whoever has uploaded the package there has implemented.

**Comment by mak448a** [comment]
Okay, thanks for the help!
