### ISSUE TITLE
`wiiuseexample-sdl` and `doc` not in makefile

### ISSUE THREAD

**Issue by RuralAnemone** [wiiuse/wiiuse#150]
I've followed the installation directions in the readme, but running `make` only compiles `wiiuse` and `wiiuseexample`. Am I missing something?

Debian 12, I have `libsdl2-dev` installed.

**Comment by janoc** [comment]
You need to enable BUILD_EXAMPLE_SDL, e.g. by running `cmake` as:

`shell
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLE_SDL=ON
`

**Comment by RuralAnemone** [comment]
oh wow I'm blind
apologies for the stupidity

thanks (:

**Comment by janoc** [comment]
Welcome.
