### ISSUE TITLE
Mailing List Archives

### ISSUE THREAD

**Issue by hendursaga** [wiiuse/wiiuse#151]
It is unclear how I could access the mailing list archives at Librelist. I cannot access the [archive link](http://librelist.com/browser/wiiuse/). There is a mention of `rsync`, but I have a feeling that might not work, either. Perhaps we could migrate or at least switch to GitHub Discussions?

**Comment by janoc** [comment]
Hello, 

I don't actually believe there ever was a mailing list for the last 15 years ... We should remove that mention from the README, it is a left-over of the ancient original text from 2011 when the repo was forked from the original dead project. 

If there is any discussion/activity then it is here in the Github issues.

**Comment by hendursaga** [comment]
Fair enough. I confirmed that the email address to subscribe does not accept mail.
