### ISSUE TITLE
If M+ reporting in example is on, plugging in nunchuk goes undetected

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#34]
Tested with the branch mentioned in #30 on Linux.  It won't see the nunchuk until you hit 2 to stop the motion+

**Comment by DacoTaco** [comment]
somebody also mentioned this in libogc , so i started looking. is this still the case?
i see the motion plus event handler seems to have some parsing for expansion packets
https://github.com/wiiuse/wiiuse/blob/master/src/motion_plus.c#L278

**Comment by janoc** [comment]
It is likely that this is still the case - Wiimote doesn't report that there is a new expansion plugged in when M+ is on - M+ is **the** expansion (and thus doesn't get disconnected, so nothing is being detected). 

There is likely some protocol/initialization that needs to be done for Wiimote/M+ to report change in the connected expansion when M+ reporting is on. 

The M+ handler will correctly deal with the expansions (e.g. Nunchuk) if you ask the M+ to send you the expansion reports including the Nunchuk data beforehand.
