### ISSUE TITLE
On Windows, motion+ and extensions don't work the second time a WiiUse app is run.

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#35]
In Win7, I pair the wiimote with motion+, with no pairing code. It stays blinking until I run a WiiUse app. The first wiiuse app can successfully turn on and off the motion+, passthrough extensions and extensions without m+ work fine.

If I close the app, then while the wiimote is still displaying the same LED state (indicating "connected"), start it or another app again, that app will not be able to activate Motion+ or recognize any extensions, whether or not they go through the M+ itself.

Workaround is to power off the Wiimote, remove the device from bluetooth devices, and re-pair.

**Comment by janoc** [comment]
This should be more robust now, Motion+ is being explicitly reset on the initial handshake to cover this situation.
