### ISSUE TITLE
wiibrew.org links to dead wiiuse.net

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#37]
It should link here.  I've made an account, but am still waiting for the confirmation email.

**Comment by rpavlik** [comment]
Could probably be updated again, since this has effectively become the official new upstream. https://wiibrew.org/wiki/Wiiuse

There are no more wiiuse.net links in the code or readme - they're either switched to the old SF project, or to an archive.org link, as appropriate.

**Comment by DacoTaco** [comment]
3 years later...
i heard there was(is?) a registration bug on wiibrew when using a phone. maybe you got hit by that?
either case, if you want me to edit it, feel free to send me the links to replace in that wiki link

**Comment by janoc** [comment]
@DacoTaco I think links on this page need to be updated:
https://wiibrew.org/wiki/Wiiuse

**Comment by DacoTaco** [comment]
ye, i figured, but to what?
the sourceforge link probably needs redirection to this github, and the rest?

**Comment by janoc** [comment]
Just point it to this Github (https://github.com/wiiuse/wiiuse), IMO. There isn't anything else.

**Comment by DacoTaco** [comment]
edits have been applied

**Comment by janoc** [comment]
Thank you!
