### ISSUE TITLE
Cherry-pick reconnect-capable example

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#40]
Patch is here: https://github.com/jzarl/wiiuse/commit/867f99a50b7bea90c5f370bf7ca75d1d9fc3ac50

Will make it easier to ensure that reconnecting works properly - I suspect there is some issue with it at present given my usage in VRPN.

**Comment by PureTryOut** [comment]
@rpavlik sadly that link you provided is dead, I guess the repo has been deleted. My own program using WiiUse is capable of reconnecting, but I'm not sure if you mean reconnecting after some error or after the user has manually disconnected the remote. The latter I could probably provide an example implementation for, the former not so much as I haven't experienced an error disconnect yet.

**Comment by rpavlik** [comment]
I think this is just an outdated pr. If you wanted to contribute an example that reconnects you're welcome to, but I'll close this since the original is no longer available.
