### ISSUE TITLE
Wrong data returned from WiiBoard in fresh build

### ISSUE THREAD

**Issue by csvurt** [wiiuse/wiiuse#42]
Running the included wiiuseexample.exe with a fresh build of wiiuse is returning wrong values for the balance board. Specifically the top left sensor always returns 0, while the other 3 are not scaled correctly. Running a debug build we get this raw data coming in:

--- EVENT [id 1] ---
Weight: 0.000000 kg @ (-1.#IND00, -1.#IND00)
[DEBUG](id 1) RECV: (34) 00 00 03 d0 19 1a 00 17 15 23 19 00 6e 00 00 00 00 00
00 00 00

Putting pressure on the top left sensor only increases its value from 0017 to 0018, which still registers as 0 after the conversion and calibration.

Strangely if we run the prebuilt wiiuse.dll (the one included in the 0.14 package) once with the example, then the freshly built dll also returns the right values, at least so long as the Wiiboard isn't turned off in between. So this might be a calibration problem, or something set in the bluetooth stack itself. We're using the native stack on Windows 7.

Reverting the repository to the commit "added forgotten Balance board support" from Jan 15th also gives the right values, but isn't very stable.

We're also having trouble disconnecting the board. Both wiiuse_disconnect and wiiuse_cleanup leave the board in a connected state (led is still on), any ideas here?

**Comment by gazialankus** [comment]
nighele88, thank you for the values for WINHD_INCLUDE_DIR etc. For people who are in the same boat as I am, I thought I'd drop here a note about what worked for me in Windows 8.1 and *Visual Studio 2015*

WINHID_CRT_INCLUDE_DIR= (empty, not set)
WINHID_INCLUDE_DIR=C:/Program Files (x86)/Windows Kits/8.1/Include (there is no "api")
WINHID_LIBRARY=C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x86/hid.lib
WINHID_ROOT_DIR= (empty, not set)

and [here](http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx) is the reason for leaving WINHID_CRT_INCLUDE_DIR blank. Search for "printf and scanf functions are now defined inline" there. It seems the stdio.h that is in C:/Program Files (x86)/Windows Kits/8.1/Include/km/crt is not compatible with MS's new stdio.h, which has printf and scanf inline in the .h file. 

Took me a while to figure this out, so I thought someone might appreciate. The example works just fine here.

**Comment by rpavlik** [comment]
FWIW, I did test with an official balance board on Windows 10 for the 0.15.4 release, and it did appear to work correctly. (Newer Visual Studio has made compilation a lot easier by including the hid includes by default, etc.)

Closing as "Fixed somehow".
