### ISSUE TITLE
Destination for install

### ISSUE THREAD

**Issue by jpffitch** [wiiuse/wiiuse#43]
On OpenSuSE x86_64 the libraries should go in /usr/lib64 or /usr/local/lib64 but I do not see an option for that.  Have I missed something, or do I need to move it by hand after it has been placed in /usr/local/lin ?

**Comment by janoc** [comment]
I believe CMake handles this now, doesn't it?

**Comment by jpffitch** [comment]
I just pulled and rebuilt -- and the answer is no, or at least not obviously.  It installed in /usr/local/lib

**Comment by janoc** [comment]
OK, pull a master and try to build it. This should fix it.

**Comment by jpffitch** [comment]
I am usng the master branch and then did
cmake build
make
make install
and it installed to /usr/local/lib

so not obviously fixed

**Comment by janoc** [comment]
Please do make sure to wipe your build folder before re-running cmake because the values are cached. 
You can also add this line to the line 50 in the CMakeLists.txt to check:
```
        message("Libraries will go to: ${CMAKE_INSTALL_LIBDIR}")
```
For me it prints out:
```
Libraries will go to: lib64
```
And make install installs to $CMAKE_INSTALL_PREFIX/lib64, as it should.

**Comment by jpffitch** [comment]
after deleting cache etc I get

xenakis:~/Audio/wiiuse> cmake build
-- Configuring WiiUse version 0.15.1
Libraries will go to:
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jpff/Audio/wiiuse/build

**Comment by janoc** [comment]
That's weird - do you have the current master that includes this line?
```
include("GNUInstallDirs")
```

The top level CMakeLists.txt should contain this block:
```
if(NOT WIN32 AND NOT APPLE)
	set(LINUX YES)
	find_package(Bluez REQUIRED)
	include_directories(${BLUEZ_INCLUDE_DIRS})

        include("GNUInstallDirs")
        message("Libraries will go to: ${CMAKE_INSTALL_LIBDIR}")
else()
        set(LINUX NO)
        set(CMAKE_INSTALL_LIBDIR "lib")
endif()
```

**Comment by jpffitch** [comment]
I am not seeing that code

xenakis:~/Audio/wiiuse> grep -r GNUInstall .
xenakis:~/Audio/wiiuse>

Also in CMakeLists.txt

if(NOT WIN32 AND NOT APPLE)
         set(LINUX YES)
         find_package(Bluez REQUIRED)
         include_directories(${BLUEZ_INCLUDE_DIRS})
else()
         set(LINUX NO)
endif()

**********BUT *******
Just did another git pull and it brought new code.  Wonder why it didnot 
earlier

Anyway now fixed

**Comment by janoc** [comment]
Very good. Thanks for the confirmation.
