### ISSUE TITLE
New nunchuk doesn't report calibration info

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#59]
cc @lpberg - Newer nunchuks (since the wii-u I think) don't return any calibration info, which screws us up. We should just deal with it and have some default.

**Comment by janoc** [comment]
Arg. We all *do love* Nintendo here, don't we?

What does it actually return? We can always dump values from an "old" Nunchuk and use those, but I am more concerned that this new behaviour will trip up the (already fragile) expansion detection/init.

**Comment by rpavlik** [comment]
I think it returns all 0, IIRC. I copied Leif since he's the one with access to one - our "workaround" at VRAC was to use my nunchuk from home instead of the one they bought.

**Comment by janoc** [comment]
If it returns all 0, that could be also because of a faulty connection/failed init.

I have seen these issues before, with the ID strings or calibration data being invalid (all FF or 0) because the expansion was in a "semi-initialized" state. It often took unplugging and re-plugging to clear it and make it work again.

**Comment by rpavlik** [comment]
I think I tried plugging/unplugging a number of times, but as I don't work at VRAC any more I don't have access to that unit.

**Comment by janoc** [comment]
This would be good to verify to make sure it is a consistent behaviour across multiple "new" nunchuks before we try to put some kludge in the code. I am more inclined to think it is either a faulty unit or some sort of communication problem with that particular Wiimote. 

If Nintendo isn't sending the calibration data, that would be quite messy - not so big deal for the joystick, but the accelerometers on the nunchucks differ in the values sent quite a bit between units.
