### ISSUE TITLE
wiiuse_find always returns 0

### ISSUE THREAD

**Issue by xoyojank** [wiiuse/wiiuse#60]
Win7 64bit, WinDDK 7.1
but I can use the Wiimote in Dolphin Emulator

**Comment by janoc** [comment]
Which Wiimote do you have? Genuine Nintendo or a clone? And which model? Original, Wiimote+ or the newest Wiimote (with the name RVL-CNT-01-TR)? How are you connecting to Wiiuse? Wiiuse doesn't support pairing with the Wiimote yet because there is no cross-platform way of handling it, so you need to put it into discoverable mode by pressing 1+2 buttons together (or push the red button in the battery compartment) and then run your application.

**Comment by xoyojank** [comment]
Nintendo RVL-CNT-01-TR

typedef enum win_bt_stack_t {
WIIUSE_STACK_UNKNOWN,
WIIUSE_STACK_MS,
WIIUSE_STACK_BLUESOLEIL
} win_bt_stack_t;

I found there are only 2 types of stack in the enum, and I used the
bluetooth stack by TOSHIBA. I start the wiiuseexample after I have
connected (the LED 1 is lighted).


Should I try another one? I installed BlueSoleil, but neither the Dolphin
Enmulator or WiiUse can find the device.

2015-04-21 20:17 GMT+08:00 janoc <notifications@github.com>:

> Which Wiimote do you have? Genuine Nintendo or a clone? And which model?
> Original, Wiimote+ or the newest Wiimote (with the name RVL-CNT-01-TR)? How
> are you connecting to Wiiuse? Wiiuse doesn't support pairing with the
> Wiimote yet because there is no cross-platform way of handling it, so you
> need to put it into discoverable mode by pressing 1+2 buttons together (or
> push the red button in the battery compartment) and then run your
> application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rpavlik/wiiuse/issues/60#issuecomment-94772751>.
>



-- 
逍遥剑客
http://blog.csdn.net/xoyojank/

**Comment by xoyojank** [comment]
I create a patch base on
https://github.com/Kalabasa/supertuxkart-remote-controller/blob/master/SuperTuxKart-0.8.1/lib/wiiuse/
and now the device can work correctly

2015-04-22 10:02 GMT+08:00 逍遥剑客 <xoyojank@gmail.com>:

> Nintendo RVL-CNT-01-TR
>
> typedef enum win_bt_stack_t {
> WIIUSE_STACK_UNKNOWN,
> WIIUSE_STACK_MS,
> WIIUSE_STACK_BLUESOLEIL
> } win_bt_stack_t;
>
> I found there are only 2 types of stack in the enum, and I used the
> bluetooth stack by TOSHIBA. I start the wiiuseexample after I have
> connected (the LED 1 is lighted).
>
>
> Should I try another one? I installed BlueSoleil, but neither the Dolphin
> Enmulator or WiiUse can find the device.
>
> 2015-04-21 20:17 GMT+08:00 janoc <notifications@github.com>:
>
>> Which Wiimote do you have? Genuine Nintendo or a clone? And which model?
>> Original, Wiimote+ or the newest Wiimote (with the name RVL-CNT-01-TR)? How
>> are you connecting to Wiiuse? Wiiuse doesn't support pairing with the
>> Wiimote yet because there is no cross-platform way of handling it, so you
>> need to put it into discoverable mode by pressing 1+2 buttons together (or
>> push the red button in the battery compartment) and then run your
>> application.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rpavlik/wiiuse/issues/60#issuecomment-94772751>.
>>
>
>
>
> --
> 逍遥剑客
> http://blog.csdn.net/xoyojank/
>



-- 
逍遥剑客
http://blog.csdn.net/xoyojank/

**Comment by janoc** [comment]
Um, what exactly did you change? Could you make a pull request with your changes, please? 

The new -RT Wiimote should be supported in the latest master branch in Git, AFAIK, but neither me nor Ryan have one of those, so it is not well tested. We are pretty much dependent on people having the hardware to submit patches here.

**Comment by janoc** [comment]
For reference, this problem is tracked here already #21 and #61

**Comment by janoc** [comment]
The 0.15.2 finally added support for the -TR wiimote, so this can be closed.
