### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Baumgartl** [wiiuse/wiiuse#93]
Hi,

is this project dead since the last commit was over a year ago? @rpavlik is absentee and I would like to know who is responsible for maintaining and reviewing all open issues and pull requests.

Have a nice day,
Baumgartl

**Comment by rpavlik** [comment]
Sorry, I haven't had time to work on this. I'd be happy to share maintenance with someone else - I think I already gave @janoc permissions on this repo.

**Comment by Baumgartl** [comment]
Thank you for your brief reply. I'm happy to see that the project goes on and I really look forward to encourage other (Nintendo) enthusiasts for joining the development team. 😃

**Comment by janoc** [comment]
Any contributors (and contributions) are certainly most welcome. Wiiuse isn't dead but it is working well enough to be used and neither @rpavlik nor me have any pressing issues with it, so the development is slow. That doesn't mean that there aren't any things that could be improved - more like exactly the opposite. 

However, that needs more developers with time to put in it. Also people with more hardware to test on and to debug problems are needed - especially things like the newer Wiimote models, Balance boards, etc. It is difficult to support/debug hardware that neither @rpavlik nor me have. 

The same for supporting Mac OS X and Windows - I am a Linux user myself, Ryan has done some of the Windows work but Windows is a big pain to handle with all those different Visual Studio/Windows SDK/OS versions. And neither of us has a Mac. So any help there would be certainly appreciated. 

There is also the need to reimplement some parts of the library to support proper pairing (most OS-es are able to pair a Wiimote today, either directly or using something like the Mayflash Dolphinbar) but Wiiuse has no idea about handling that. Lots of things could use rewriting for better robustness, etc ... 

So if someone wants to contribute, they are very very welcome.

**Comment by dvzrv** [comment]
@janoc @rpavlik would it be possible for you to release a new version then (as mentioned in #92).
New versions and adoption in pre-compiled repositories usually lead to more users, ergo more people at least potentially being interested and willing to work on a project

**Comment by janoc** [comment]
I will ping @rpavlik, he likely doesn't follow Github messages.

**Comment by rpavlik** [comment]
OK, just moved the repo to an org of its own, tagged 0.15.1, and updated the readme to indicate why it doesn't change. If anybody wants commit access who has already submitted a patch, just ping me.
