### ISSUE TITLE
Remove references to github.com/rpavlik/wiiuse

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#97]
Minor issue - the project has been moved to its own "organization" so the url is now https://github.com/wiiuse/wiiuse

I thought I fixed it all, but there's a startup message that still refers to the old URL.

**Comment by janoc** [comment]
Arg. I guess the 0.15.x series of brown paper bag releases is going to be long :-)

**Comment by rpavlik** [comment]
:D perhaps - give me a few minutes and I'll reboot a computer into windows to try that

**Comment by janoc** [comment]
There are actually quite a few places where rpavlik github repo is mentioned - Changelog, Readme, wiiuse.[ch] and a some of the CMake modules (btw, do we really need all of those, including stuff like VRJuggler?)

**Comment by rpavlik** [comment]
re the cmake modules - I am just following the instructions on the cmake-modules repo for maintaining as a sub-tree.
