### ISSUE TITLE
.clang-format file

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#98]
Looks like @janoc used clang-format but didn't commit the config file to the repo. Would be good to have that committed.

**Comment by janoc** [comment]
I can commit that when I am back home in about an hour. Didn't think that was something to be used more than once because it messes up some things that I had to fix by hand later - e.g. #include ordering and alignment of some constants for readability.

**Comment by rpavlik** [comment]
Ok, no problem. I do like to do, e.g. git clang-format which only reformats
the lines touched by staged changes.

**Comment by janoc** [comment]
I normally do the same but the indentation was too messed up to fix piecewise. Mixed tabs and spaces, inconsistent indentation after years of merges, etc.
